services:
  # 0. Frontend
  frontend-service:
    build: ./frontend-service
    container_name: frontend-service
    ports:
      - "3000:80"
    depends_on:
      - gateway-service
    networks:
      - pamvid-network

  # 1. API Gateway
  gateway-service:
    build: ./gateway-service
    container_name: gateway-service
    ports:
      - "8080:80"
    depends_on:
      - order-service
      - payment-service
      - product-service
      - sales-service
      - user-service
      - notification-service
    networks:
      - pamvid-network

  # 2. Capa de Servicios
  order-service:
    build: ./order-service
    container_name: order-service
    environment:
      - DATABASE_URL=postgresql://neondb_owner:npg_ZwStrQ3RbPc1@ep-autumn-art-amm4xi1w-pooler.c-5.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
    networks:
      - pamvid-network

  payment-service:
    build: ./payment-service
    container_name: payment-service
    environment:
      - DATABASE_URL=postgresql://neondb_owner:npg_ZwStrQ3RbPc1@ep-autumn-art-amm4xi1w-pooler.c-5.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
    networks:
      - pamvid-network

  product-service:
    build: ./product-service
    container_name: product-service
    environment:
      - DATABASE_URL=postgresql://neondb_owner:npg_ZwStrQ3RbPc1@ep-autumn-art-amm4xi1w-pooler.c-5.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
    networks:
      - pamvid-network

  sales-service:
    build: ./sales-service
    container_name: sales-service
    environment:
      - DATABASE_URL=postgresql://neondb_owner:npg_ZwStrQ3RbPc1@ep-autumn-art-amm4xi1w-pooler.c-5.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
    networks:
      - pamvid-network

  user-service:
    build: ./user-service
    container_name: user-service
    environment:
      - DATABASE_URL=postgresql://neondb_owner:npg_ZwStrQ3RbPc1@ep-autumn-art-amm4xi1w-pooler.c-5.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
    networks:
      - pamvid-network

  notification-service:
    build: ./notification-service
    container_name: notification-service
    environment:
      - DATABASE_URL=postgresql://neondb_owner:npg_ZwStrQ3RbPc1@ep-autumn-art-amm4xi1w-pooler.c-5.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
    networks:
      - pamvid-network

  # 3. Capa de Persistencia (Base de datos en la nube - Neon)
  # Eliminamos las bases de datos locales ya que usamos Neon para todos los servicios

networks:
  pamvid-network:
    external: false