version: '3.8'

services:
  # 0. Frontend
  frontend-service:
    build: ./frontend-service
    container_name: frontend-service
    ports:
      - "3000:80"
    depends_on:
      - gateway-service
    networks:
      - pamvid-network

  # 1. API Gateway
  gateway-service:
    build: ./gateway-service
    container_name: gateway-service
    ports:
      - "8080:80"
    depends_on:
      - order-service
      - payment-service
      - product-service
      - sales-service
    networks:
      - pamvid-network

  # 2. Capa de Servicios
  order-service:
    build: ./order-service
    container_name: order-service
    environment:
      - DATABASE_URL=postgresql://user:pass@db-orders:5432/orders_db
    depends_on:
      - db-orders
    networks:
      - pamvid-network

  payment-service:
    build: ./payment-service
    container_name: payment-service
    environment:
      - DATABASE_URL=postgresql://user:pass@db-payments:5432/payments_db
    depends_on:
      - db-payments
    networks:
      - pamvid-network

  product-service:
    build: ./product-service
    container_name: product-service
    environment:
      - DATABASE_URL=postgresql://neondb_owner:npg_ZwStrQ3RbPc1@ep-autumn-art-amm4xi1w-pooler.c-5.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
    networks:
      - pamvid-network

  sales-service:
    build: ./sales-service
    container_name: sales-service
    environment:
      - DATABASE_URL=postgresql://user:pass@db-sales:5432/sales_db
    depends_on:
      - db-sales
      - product-service
    networks:
      - pamvid-network

  # 3. Capa de Persistencia (Bases de Datos)
  db-orders:
    image: postgres:15
    container_name: db-orders
    ports:
      - "5431:5432" # Puerto para DBeaver
    environment:
      POSTGRES_DB: orders_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    volumes:
      - pgdata_orders:/var/lib/postgresql/data
    networks:
      - pamvid-network

  db-payments:
    image: postgres:15
    container_name: db-payments
    ports:
      - "5432:5432" # Puerto estándar (si no tienes Postgres en Windows)
    environment:
      POSTGRES_DB: payments_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    volumes:
      - pgdata_payments:/var/lib/postgresql/data
    networks:
      - pamvid-network

  db-products:
    image: postgres:15
    container_name: db-products
    ports:
      - "5433:5432" # Puerto para DBeaver
    environment:
      POSTGRES_DB: products_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    volumes:
      - pgdata_products:/var/lib/postgresql/data
    networks:
      - pamvid-network

  db-sales:
    image: postgres:15
    container_name: db-sales
    ports:
      - "5434:5432" # Puerto para DBeaver
    environment:
      POSTGRES_DB: sales_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    volumes:
      - pgdata_sales:/var/lib/postgresql/data
    networks:
      - pamvid-network

networks:
  pamvid-network:
    external: false

volumes:
  pgdata_orders:
  pgdata_payments:
  pgdata_products:
  pgdata_sales: